---
run:
  tests: false

linters:
  disable:
    - gosec
    - gochecknoglobals
    - godox # TODO(mbaillie): remove once other TODOs are fixed!

issues:
  max-same-issues: 0
  max-per-linter: 0

linters-settings:
  funlen:
    lines: 80
    statements: 60
