{
 "title": "Vault GitHub",
 "tags": [ "cloacineria" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Token Creation Successes Over Period",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(round(increase(vault_github_token_request_duration_seconds_count{success=\"true\"}[$__range]))) without (permissions, repository_ids)"
    }
   ]
  },
  {
   "title": "Token Creation Failures Over Period",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(round(increase(vault_github_token_request_duration_seconds_count{success!=\"true\"}[$__range]))) without (permissions,repository_ids)) > 0"
    }
   ]
  },
  {
   "title": "Plugin Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "vault_github_token_build_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Token Creation Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(vault_github_token_request_duration_seconds) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}