---
version: '3'
#########################################################################
# NOTE: This docker-compose should be interfaced only via the Makefile. #
#########################################################################
volumes:
  go-pkg:
  go-bin:

services:
  golang: &golang
    # golang 1.13.4 (debian)
    image: golang@sha256:f9de064473fb30c66bc0d2ddf2cf9a4a9bd38cbd2c5e59ce3bdf8af7b8747a57
    network_mode: bridge
    environment:
      - PROJECT
      - PACKAGE
      - SKIP_TEST
      - SKIP_LINT
      - CI
    working_dir: /go/src/${PACKAGE}
    volumes:
      - .:/go/src/${PACKAGE}
      - go-pkg:/go/pkg
      - go-bin:/go/bin

  make:
    <<: *golang
    entrypoint: make
